### ISSUE TITLE
genericCLI segfault in ndn::Name::appendTimestamp

### ISSUE THREAD

**Issue by yoursunny** [pollere/DNMP#4]
Environment:

* Ubuntu 18.04 amd64
* ndn-cxx and NFD 0.7.0 with [build-system.patch](https://github.com/pollere/NDNpatches/blob/6ce2cbf63c5ca7d019e70ca410813b27be282ce2/build-system.patch), installed from source code, sample `nfd.conf`
* g++-8 compiler
* DNMP commit 4c34e0fdd3a32061bcffd78e34611e4cfee57143

Steps to reproduce:

1. `nfd-start`
2. `./nod`
3. ` ./genericCLI -p NFDGeneralStatus`

Expected: the program prints NFD version and other information
Actual:
```
Thread 1 "genericCLI" received signal SIGSEGV, Segmentation fault.
ndn::Name::appendTimestamp (this=0x7fffffffd770,
    timestamp=<error reading variable: Cannot access memory at address 0x0>)
    at ../ndn-cxx/name.cpp:238
238       return append(Component::fromTimestamp(timestamp.value_or(time::system_clock::now())));
(gdb) bt
#0  ndn::Name::appendTimestamp (this=0x7fffffffd770,
    timestamp=<error reading variable: Cannot access memory at address 0x0>)
    at ../ndn-cxx/name.cpp:238
#1  0x000055555557b6a6 in CRshim::buildCmd (a="", s="NFDGeneralStatus",
    this=0x7fffffffdf60) at /usr/include/c++/8/optional:969
#2  CRshim::issueCmd(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (Reply const&, CRshim&)> const&) (this=this@entry=0x7fffffffdf60, ptype="NFDGeneralStatus", pargs="",
    rh=...) at CRshim.hpp:154
#3  0x0000555555566eea in sendCommand(CRshim&) () at /usr/include/c++/8/new:169
#4  0x0000555555564e2b in main () at generic-client.cpp:181
#5  0x00007ffff666ab97 in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
#6  0x0000555555564eba in _start () at /usr/local/include/ndn-cxx/name.hpp:43
```

If DNMP was compiled with `clang++-8` instead, the segfault does not occur, but the program does not produce any output.

**Comment by kmnichols** [comment]
That's an older Ubuntu that we are currently running. We are using 20.04, though we previously used 19.04. We are currently using g++ version 9.
Your symptoms sound like ones we've experienced when updating compilers if we didn't recompile the entire tool chain (all the libraries) with the same compiler.
